services:
  - type: web
    name: n8n
    env: docker
    plan: free
    repo: https://github.com/tuusuario/tu-repo
    branch: main
    dockerfilePath: ./Dockerfile
    envVars:
      - key: N8N_BASIC_AUTH_ACTIVE
        value: true
      # ⚠️ Usuario y contraseña se agregan en Render, no aquí
    autoDeploy: true
