services:
  - type: web
    name: n8n
    env: docker
    plan: free
    repo: https://github.com/tuusuario/tu-repo
    branch: main
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: N8N_BASIC_AUTH_ACTIVE
        sync: false
      - key: N8N_BASIC_AUTH_USER
        sync: false
      - key: N8N_BASIC_AUTH_PASSWORD
        sync: false

